trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: NpmAuthenticate@0
  inputs:
    workingFile: .npmrc

- script: |
    npm install
    npm run build
    npm pack
  displayName: 'Build and Pack User Management Module'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'
    artifact: 'user-management-package'

- task: Npm@1
  displayName: 'Publish Npm Package'
  inputs:
    command: "publish"
    workingDirectory: $(System.DefaultWorkingDirectory)
    publishRegistry: useFeed
    publishFeed: user-management-api

